# Generated by Django 4.2.1 on 2023-06-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0006_post_likes_delete_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='user_that_likes',
        ),
    ]
