# Generated by Django 4.2.1 on 2023-06-07 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialnetwork', '0007_rename_likes_post_user_that_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_that_likes',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
